name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      input1:
        type: string
        description: Something
        required: false
        default: Blah
    secrets:
      some-secret:
        required: true
    outputs:
      result:
        description: The Result, duh!
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: echo "Deploying...${{ secrets.some-secret }}"
      - name: Set result output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
