name: Reusable Deploy
on: 
  workflow_call:
    inputs:
      input1:
        type: string
        description: Something
        required: false
        default: Blah
    secrets:
      some-secret:
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: echo "Deploying...${{ secrets.some-secret }}"
